pub const NOUNS: &[(&str, &str)] = &[
    ("der", "Bruder"),
    ("der", "Junge"),
    ("der", "Hund"),
    ("der", "Mann"),
    ("der", "Vater"),
    ("der", "Sohn"),
    ("der", "Winter"),
    ("der", "Knödel"),
    ("der", "Kaffee"),
    ("der", "Tee"),
    ("der", "Wein"),
    ("die", "Frau"),
    ("die", "Tochter"),
    ("die", "Katze"),
    ("die", "Milch"),
    ("die", "Mutter"),
    ("die", "Schwester"),
    ("das", "Auge"),
    ("das", "Bier"),
    ("das", "Brot"),
    ("das", "Wasser"),
];
